spring:
  application:
    name: zshop
  datasource:
    url: jdbc:postgresql://localhost:5432/zshop
    username: aayush
    password: Aayush@123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 3000